name: Daily Auto Commit

on:
  schedule:
    # Runs at 12:00 UTC (adjust as needed)
    - cron: '0 12 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Need to use token with permission to push
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Create/Update Daily Log and README
        run: |
          # Get the date and quote
          CURRENT_DATE=$(date)
          SYSTEM_INFO=$(uname -a)
          QUOTE_DATA=$(curl -s https://api.quotable.io/random)
          QUOTE_CONTENT=$(echo $QUOTE_DATA | jq -r '.content')
          QUOTE_AUTHOR=$(echo $QUOTE_DATA | jq -r '.author')
          
          # Update the log file
          echo "Last updated: $CURRENT_DATE" > update_log.txt
          echo "System info: $SYSTEM_INFO" >> update_log.txt
          echo "Random quote of the day: $QUOTE_CONTENT - $QUOTE_AUTHOR" >> update_log.txt
          
          # Check if README exists
          if [ -f README.md ]; then
            # Check if the README already has a quote section
            if grep -q "## Today's Quote" README.md; then
              # Update existing quote section using sed
              sed -i '/## Today'"'"'s Quote/,/^$/c\## Today'"'"'s Quote\n\n> '"$QUOTE_CONTENT"'\n> \n> — *'"$QUOTE_AUTHOR"'*\n\nLast updated: '"$CURRENT_DATE"'\n' README.md
            else
              # Append quote section to the end of the README
              echo -e "\n## Today's Quote\n\n> $QUOTE_CONTENT\n> \n> — *$QUOTE_AUTHOR*\n\nLast updated: $CURRENT_DATE\n" >> README.md
            fi
          else
            # Create a new README with the quote
            echo -e "# Daily Auto Commit\n\nThis repository demonstrates automation with GitHub Actions.\n\n## Today's Quote\n\n> $QUOTE_CONTENT\n> \n> — *$QUOTE_AUTHOR*\n\nLast updated: $CURRENT_DATE\n" > README.md
          fi
      
      - name: Commit and Push
        run: |
          git add .
          git commit -m "this project cheeses my github" || echo "No changes to commit"
          git push origin HEAD
