name: Daily Auto Commit
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      
      - name: Create Update Script
        run: |
          cat > update.sh << 'ENDSCRIPT'
          #!/bin/bash
          
          # Get quote with better error handling
          echo "Fetching quote..."
          QUOTE_RESPONSE=$(curl -s https://api.quotable.io/random)
          
          # Debug - see what we got
          echo "API Response: $QUOTE_RESPONSE"
          
          # Check if we got a valid JSON response
          if echo "$QUOTE_RESPONSE" | jq -e . >/dev/null 2>&1; then
            echo "Valid JSON response received"
            QUOTE_CONTENT=$(echo "$QUOTE_RESPONSE" | jq -r '.content')
            QUOTE_AUTHOR=$(echo "$QUOTE_RESPONSE" | jq -r '.author')
          else
            echo "Invalid response, using fallback quote"
            QUOTE_CONTENT="Every day is a chance to automate something new."
            QUOTE_AUTHOR="A Wise Developer"
          fi
          
          # Debug - print extracted values
          echo "Quote content: $QUOTE_CONTENT"
          echo "Quote author: $QUOTE_AUTHOR"
          
          DATE=$(date)
          
          # Update log file
          echo "Last updated: $DATE" > update_log.txt
          echo "System info: $(uname -a)" >> update_log.txt
          echo "Quote: $QUOTE_CONTENT - $QUOTE_AUTHOR" >> update_log.txt
          
          # Create the new README content
          echo "# Daily Auto Commit" > README.md
          echo "This repository demonstrates my ability to automate GitHub workflows using GitHub Actions." >> README.md
          echo "## What it does" >> README.md
          echo "- Runs automatically every day at 12:00 UTC" >> README.md
          echo "- Updates a log file with the current date and system information" >> README.md
          echo "- Fetches a random quote from an API" >> README.md
          echo "- **Updates this README with the quote of the day**" >> README.md
          echo "- Commits and pushes these changes automatically" >> README.md
          echo "## Why I built this" >> README.md
          echo "This project showcases my technical abilities with:" >> README.md
          echo "- GitHub Actions and CI/CD workflows" >> README.md
          echo "- Automation scripts" >> README.md
          echo "- Git operations from within workflows" >> README.md
          echo "- Working with external APIs" >> README.md
          echo "- Dynamic content generation" >> README.md
          echo "- *Most importantly, it shows how green boxes really dont mean much in terms of skills.*" >> README.md
          echo "## How it works" >> README.md
          echo "The GitHub Action workflow:" >> README.md
          echo "1. Runs on a schedule (daily)" >> README.md
          echo "2. Fetches a random inspirational quote" >> README.md
          echo "3. Updates both a log file and this README" >> README.md
          echo "4. Commits and pushes the changes" >> README.md
          echo "## Today's Quote" >> README.md
          echo "" >> README.md
          echo "> $QUOTE_CONTENT" >> README.md
          echo ">" >> README.md
          echo "> — *$QUOTE_AUTHOR*" >> README.md
          echo "" >> README.md
          echo "Last updated: $DATE" >> README.md
          ENDSCRIPT
          
          chmod +x update.sh
      
      - name: Run Update Script
        run: ./update.sh
      
      - name: Commit changes
        run: |
          git add .
          git commit -m "this project cheeses my github" || true
          git push
